### ISSUE TITLE
Make use of Kapitan Compile Cache

### ISSUE THREAD

**Issue by srueg** [projectsyn/commodore#123]
When Kapitan is called with `kapitan compile --cache` is called, a cache file is created in the `compiled/` directory. This file contains the hashes of all input values (classes and parameters). Before compiling the catalog, Kapitan can calculate these hashes and compare them to the current ones. If they didn't change, the compilation won't change anything and can be skipped.

` .kapitan_cache`
```yaml
folder: {}
inventory:
  cluster:
    classes: ff5655c9b1f7c742936a02cd0399236f649531c2293f98c7a836d2fcc7036729
    parameters: 002430ede00ab44b0677e163eda31fc369b2706f4dba2a4dfe1bab6c5f1ab811
```

To make use of this, the following changes are required:

- [ ] Verify the actual caching mechanism and if our assumptions are correct
- [ ] Enable the `--cache` when calling Kapitan
- [ ] Copy the `.kapitan_cache` from `catalog/` to `compiled/` before compilation
- [ ] Copy the `.kapitan_cache` from `compiled/` to `catalog/` after compilation (and make sure it's commited)

Since we have to clone all inventory & component repos anyway this won't speed up the compilation very much at first. But once we implemented a caching mechanism for all git repos, this could have a large impact.
