### ISSUE TITLE
Fake Components During Discovery

### ISSUE THREAD

**Issue by srueg** [projectsyn/commodore#138]
## Context
During discovery, all components are being cloned, even ones that are not included for the current cluster. Faking the components in this step could improve performance a lot. Additionally would it lower the side effects components can have to each other. 
After the inventory is built, the actually included components of a cluster can be cloned.

**Comment by srueg** [comment]
Using the reclass "Ignore class not found" feature we might not even have to fake the component classes: https://github.com/salt-formulas/reclass/blob/develop/README-extensions.rst#ignore-class-not-found

**Comment by srueg** [comment]
The problem with this approach is, that if the inventory references values from a component defaults.yml it will break.
For example in `eks.yml`:
```yaml
parameters:
  synsights:
    alertmanager:
      config:
        route:
          # Set default receiver to Signalilo
          receiver: ${synsights_signalilo:alertmanager_receiver:name}
```
This will fail because the signalilo component is not yet available.
