### ISSUE TITLE
Introduce meta-parameter which components can use instead of hardcoding their base directory location

### ISSUE THREAD

**Issue by simu** [projectsyn/commodore#241]
## Context

This idea came up in a discussion regarding handling of shifting component directory paths when compiling components standalone (e.g. for component testing, cf. https://github.com/projectsyn/component-espejo/pull/8).

Currently components need to hard code where they want to save their dependencies to. For catalog compilation to work, this will usually be `dependencies/<component-name>/path/to/dep`.

However, when compiling a component outside a Commodore working directory, this does not really work. 

## Proposal

One way to avoid this issue is to change Commodore to provide a meta-parameter to each component which contains a path to the directory of the component, e.g. `parameters.<component_name>._base_directory`.

Components can then define their dependencies as

```
parameters:
  kapitan:
    dependencies:
      - type: https
        source: https://.../crds.yaml
        output_path: ${<component_name>:_base_directory}/manifests/.../crds.yaml
```

We've got precedence for such meta-parameters in #221 where we introduce `parameters.<component_name>._instance` to uniquely identify component instances.

## Alternatives

The current implementation is an alternative.

**Comment by ccremer** [comment]
Would this also work when the git repo of the component is different than the actual component name? (e.g. repo is `component-espejo`, but it only compiles when the root dir is called `espejo`)

**Comment by srueg** [comment]
Could we also just use `parameters._base_directory`? Since we have a separate target for each component they shouldn't collide and it would make it a little bit nicer to work with it:
```
parameters:
  kapitan:
    dependencies:
      - type: https
        source: https://.../crds.yaml
        output_path: ${_base_directory}/manifests/.../crds.yaml
```

The same could be said for the `_instance` parameter?
