### ISSUE TITLE
Different component and class nameing causes human errors applying version locks

### ISSUE THREAD

**Issue by megian** [projectsyn/commodore#319]
The version lock of components is currently based on the definition of adding a specific version to the component:
```
parameters:
  components:
    openshift4-monitoring:
      version: v1.0.0
```
Which is pretty fine, but since the class parameters having a different naming:
```
parameters:
  openshift4_monitoring:
      global:
        opsgenie_api_key: ...
```

## Actual Behavior
There is a high risk of people just copy the class name for the component version pinning and vise versa.

## Expected Behavior
Replace the class name characters from _ to - would prevent causing big trouble, when version locks are not taken.
